ALTER TABLE `jobs` 
ADD COLUMN IF NOT EXISTS `for_sale` BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS `sale_price` INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `owner_identifier` VARCHAR(60) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `owner_firstname` VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `owner_lastname` VARCHAR(50) DEFAULT NULL;